
pipelines:
  default:
    - step:
        name: Build release and unit-test
        image: royvandam/cicd:ubuntu19.10-clang-cmake

        script:
          - mkdir -p build
          - cd build
          - cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release ..
          - make -j install
          - ctest --no-compress-output -T test || true
          - mv Testing test-results
          - cd ..

        artifacts: 
          - build/install/**
          - build/test-results/**
    - step:
        name: Build debug and unit-test
        image: royvandam/cicd:ubuntu19.10-clang-cmake

        script:
          - mkdir -p build
          - cd build
          - cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Debug ..
          - make -j install
          - ctest --no-compress-output -T test || true
          - mv Testing test-results
          - cd ..

        artifacts: 
          - build/install/**
          - build/test-results/**
    - step:
        name: Build debug, unit-test and coverage
        image: royvandam/cicd:ubuntu19.10-clang-cmake

        script:
          - mkdir -p build
          - cd build
          - cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON ..
          - make test-coverage
          - cd ..

        artifacts: 
          - build/test-coverage/**